const shopBoxData = [
{ 
  id: "shoplist1", 
  src: "../img/images/01.핫써머 릴렉스핏 풀집업 래쉬가드.jpg",
  imgHidden: "../img/images/01-1.핫써머 릴렉스핏 풀집업 래쉬가드.jpg",
  imgHidden2: "../img/images/01-2.핫써머 릴렉스핏 풀집업 래쉬가드.jpg",
  gender: "남성",
  shopName : "핫써머 릴렉스핏 풀집업 래쉬가드",
  shopPrice : "89,000원",
  color: ['black'],
  style: ['스윔웨어' ,'온라인 단독', '바람막이/아노락' ,'전체보기'],
  sports : ['트레이닝' , '러닝'],
  size : ['100' ,'105', '110', '115'],
},
{ 
  id: "shoplist2", 
  src: "../img/images/02.핫써머 릴렉스핏 래쉬가드.jpg",
  imgHidden: "../img/images/02-1.핫써머 릴렉스핏 래쉬가드.jpg",
  imgHidden2: "../img/images/02-2.핫써머 릴렉스핏 래쉬가드.jpg",
  gender: "남성",
  shopName : "핫써머 릴렉스핏 래쉬가드",
  shopPrice : "79,000원",
  color: ['black'],
  style: ['스윔웨어', '온라인 단독','바람막이/아노락' ,'전체보기' ,'후드티/맨투맨'],
  sports : ['트레이닝' , '러닝'],
  size : ['100' ,'105', '110', '115'],
},
{ 
  id: "shoplist3", 
  src: "../img/images/03.컴포트핏 인터내셔널 반팔 카라티.jpg",
  imgHidden: "../img/images/03-1.컴포트핏 인터내셔널 반팔 카라티.jpg",
  imgHidden2: "../img/images/03-2.컴포트핏 인터내셔널 반팔 카라티.jpg",
  gender: "공용",
  shopName : "컴포트핏 인터내셔널 반팔 카라티",
  shopPrice : "69,000원",
  color: ['white', 'wheat'],
  style: ['티셔츠', '온라인 단독' ,'전체보기'],
  sports : ['라이프스타일' , '테니스' , '골프'],
  size : ['95','100' ,'105', '110'],
},
{ 
  id: "shoplist4", 
  src: "../img/images/04.인터내셔널 스몰 로고 티셔츠.jpg",
  imgHidden: "../img/images/04-1.인터내셔널 스몰 로고 티셔츠.jpg",
  imgHidden2: "../img/images/04-2.인터내셔널 스몰 로고 티셔츠.jpg",
  gender: "공용 컴포트핏 라이프스타일",
  shopName : "인터내셔널 스몰 로고 티셔츠",
  shopPrice : "39,000원",
  color: ['black', 'blue'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일' , '테니스' , '골프'],
  size : ['95','100' ,'105', '110'],
},
{ 
  id: "shoplist5", 
  src: "../img/images/05.인터내셔널 반팔 카라티.jpg",
  imgHidden: "../img/images/05-1.인터내셔널 반팔 카라티.jpg",
  imgHidden2: "../img/images/05-2.인터내셔널 반팔 카라티.jpg",
  gender: "공용 컴포트핏 라이프스타일",
  shopName : "인터내셔널 반팔 카라티",
  shopPrice : "69,000원",
  color: ['blue'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일' , '테니스' , '골프'],
  size : ['95','100' ,'105', '110'],
},
{ 
  id: "shoplist6", 
  src: "../img/images/06.스포츠 인터내셔널 로고 반팔티.jpg",
  imgHidden: "../img/images/06-1.스포츠 인터내셔널 로고 반팔티.jpg",
  imgHidden2: "../img/images/06-2.스포츠 인터내셔널 로고 반팔티.jpg",
  gender: "공용 컴포트핏 라이프스타일",
  shopName : "스포츠 인터내셔널 로고 반팔티",
  shopPrice : "49,000원",
  color: ['white', 'black', 'pink', 'yellow'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일' , '테니스'],
  size : ['95','100' ,'105', '110'],
},
{ 
  id: "shoplist7", 
  src: "../img/images/07.인터내셔널 그래픽 반팔티.jpg",
  imgHidden: "../img/images/07-1.인터내셔널 그래픽 반팔티.jpg",
  imgHidden2: "../img/images/07-2.인터내셔널 그래픽 반팔티.jpg",
  gender: "공용 오버핏 라이프스타일",
  shopName : "인터내셔널 그래픽 반팔티",
  shopPrice : "49,000원",
  color:['white', 'black', 'yellow'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일'],
  size : ['90', '95','100' ,'105', '110'],
},
{ 
  id: "shoplist8", 
  src: "../img/images/08.인터내셔널 그래픽 반팔티.jpg",
  imgHidden: "../img/images/08-1.인터내셔널 그래픽 반팔티.jpg",
  imgHidden2: "../img/images/08-2.인터내셔널 그래픽 반팔티.jpg",
  gender: "공용 오버핏 라이프스타일",
  shopName : "인터내셔널 그래픽 반팔티",
  shopPrice : "49,000원",
  color:['white', 'black', 'yellow'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일'],
  size : ['90', '95','100' ,'105', '110'],
},
{ 
  id: "shoplist9", 
  src: "../img/images/09.핫써머 Joyful 나시티.jpg",
  imgHidden: "../img/images/09-1.핫써머 Joyful 나시티.jpg",
  imgHidden2: "../img/images/09-2.핫써머 Joyful 나시티.jpg",
  gender: "남성 라이프스타일",
  shopName : "핫써머 Joyful 나시티",
  shopPrice : "45,000원",
  color:['black', 'orange'],
  style: ['스윔웨어' ,'트레이닝' , '세트' ,'전체보기'],
  sports : ['트레이닝' ,'러닝', '라이프스타일'],
  size : ['90', '95','100' ,'105'],
},
{ 
  id: "shoplist10", 
  src: "../img/images/10.핫써머 Fila festa 나시티.jpg",
  imgHidden: "../img/images/10-1.핫써머 Fila festa 나시티.jpg",
  imgHidden2: "../img/images/10-2.핫써머 Fila festa 나시티.jpg",
  gender: "남성 컴포트핏 라이프스타일",
  shopName : "핫써머 Fila festa 나시티",
  shopPrice : "39,000원",
  color:['white', 'black', 'blue'],
  style: ['스윔웨어' , '트레이닝' ,'세트' ,'전체보기'],
  sports : ['트레이닝' ,'러닝' ,'라이프스타일'],
  size : ['90', '95','100' ,'105'],
},
{ 
  id: "shoplist11", 
  src: "../img/images/11.페스타 그래픽 티셔츠.jpg",
  imgHidden: "../img/images/11-1.페스타 그래픽 티셔츠.jpg",
  imgHidden2: "../img/images/11-2.페스타 그래픽 티셔츠.jpg",
  gender: "공용 레귤러핏 라이프스타일",
  shopName : "페스타 그래픽 티셔츠",
  shopPrice : "49,000원",
  color:['white', 'orange', 'yellow'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일' ,'러닝'],
  size : ['90', '95','100' ,'105'],
},
{ 
  id: "shoplist12", 
  src: "../img/images/12.컴포트핏 인터내셔널 6부 반바지.jpg",
  imgHidden: "../img/images/12-1.컴포트핏 인터내셔널 6부 반바지.jpg",
  imgHidden2: "../img/images/12-2.컴포트핏 인터내셔널 6부 반바지.jpg",
  gender: "공용 라이프스타일",
  shopName : "컴포트핏 인터내셔널 6부 반바지",
  shopPrice : "59,000원",
  color:['blue'],
  style: ['팬츠' ,'트레이닝 세트' ,'전체보기'],
  sports : ['라이프스타일' ,'러닝' ,'테니스'],
  size : ['90', '95','100' ,'105'],
},
{ 
  id: "shoplist13", 
  src: "../img/images/13.레터링 그래픽 티셔츠.jpg",
  imgHidden: "../img/images/13-1.레터링 그래픽 티셔츠.jpg",
  imgHidden2: "../img/images/13-2.레터링 그래픽 티셔츠.jpg",
  gender: "공용 컴포트핏 라이프스타일",
  shopName : "레터링 그래픽 티셔츠",
  shopPrice : "49,000원",
  color:['white', 'wheat', 'orange'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일' ,'러닝' ,'테니스'],
  size : ['90', '95','100' ,'105', '110'],

},
{ 
  id: "shoplist14", 
  src: "../img/images/14.레코드 그래픽 티셔츠.jpg",
  imgHidden: "../img/images/14-1.레코드 그래픽 티셔츠.jpg",
  imgHidden2: "../img/images/14-2.레코드 그래픽 티셔츠.jpg",
  gender: "공용 컴포트핏 라이프스타일",
  shopName : "레코드 그래픽 티셔츠",
  shopPrice : "59,000원",
  color:['white', 'black', 'wheat'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일' ,'러닝' ,'테니스'],
  size : ['90', '95','100' ,'105', '110'],
},
{ 
  id: "shoplist15", 
  src: "../img/images/15.핫써머 우븐 포켓 반바지.jpg",
  imgHidden: "../img/images/15-1.핫써머 우븐 포켓 반바지.jpg",
  imgHidden2: "../img/images/15-2.핫써머 우븐 포켓 반바지.jpg",
  gender: "남성 라이프스타일",
  shopName : "핫써머 우븐 포켓 반바지",
  shopPrice : "69,000원",
  color:['orange', 'pink', 'yellow'],
  style: ['팬츠', '트레이닝 세트' ,'전체보기'],
  sports : ['라이프스타일' ,'러닝' ,'테니스'],
  size : ['90', '95','100' ,'105', '110'],
},
{ 
  id: "shoplist16", 
  src: "../img/images/16.핫써머 모노그램 나시티.jpg",
  imgHidden: "../img/images/16-1.핫써머 모노그램 나시티.jpg",
  imgHidden2: "../img/images/16-2.핫써머 모노그램 나시티.jpg",
  gender: "남성 컴포트핏 라이프스타일",
  shopName : "핫써머 모노그램 나시티",
  shopPrice : "49,000원",
  color:['blue'],
  style: ['스윔웨어' ,'트레이닝 세트' ,'전체보기'],
  sports : ['라이프스타일' , '러닝'],
  size : ['100' ,'105', '110' ,'115'],
},
{ 
  id: "shoplist17", 
  src: "../img/images/17.핫써머 씨어서커 우븐반바지.jpg",
  imgHidden: "../img/images/17-1.핫써머 씨어서커 우븐반바지.jpg",
  imgHidden2: "../img/images/17-2.핫써머 씨어서커 우븐반바지.jpg",
  gender: "공용 라이프스타일",
  shopName : "핫써머 씨어서커 우븐반바지",
  shopPrice : "69,000원",
  color:['blue'],
  style: ['팬츠', '트레이닝 세트' ,'전체보기'],
  sports : ['라이프스타일' , '트레이닝'],
  size : ['95', '100' ,'105', '110'],
},
{ 
  id: "shoplist18", 
  src: "../img/images/18.핫써머 씨어서커 아노락 바람막이.jpg",
  imgHidden: "../img/images/18-1.핫써머 씨어서커 아노락 바람막이.jpg",
  imgHidden2: "../img/images/18-2.핫써머 씨어서커 아노락 바람막이.jpg",
  gender: "공용 라이프스타일",
  shopName : "핫써머 씨어서커 아노락 바람막이",
  shopPrice : "119,000원",
  color:['blue'],
  style: ['바람막이/아노락' ,'전체보기'],
  sports : ['라이프스타일' , '트레이닝'],
  size : ['100' ,'105', '110' ,'115'],
},
{ 
  id: "shoplist19", 
  src: "../img/images/19.핫써머 사이드프린트 우븐 반바지.jpg",
  imgHidden: "../img/images/19-1.핫써머 사이드프린트 우븐 반바지.jpg",
  imgHidden2: "../img/images/19-2.핫써머 사이드프린트 우븐 반바지.jpg",
  gender: "공용 레귤러핏 라이프스타일",
  shopName : "핫써머 사이드프린트 우븐 반바지",
  shopPrice : "69,000원",
  color:['black', 'yellow'],
  style: ['티셔츠' ,'전체보기'],
  sports : ['라이프스타일' , '트레이닝'],
  size : ['95', '100' ,'105', '110'],
},
{ 
  id: "shoplist20", 
  src: "../img/images/20.레코드 그래픽 티셔츠.jpg",
  imgHidden: "../img/images/20-1.레코드 그래픽 티셔츠.jpg",
  imgHidden2: "../img/images/20-2.레코드 그래픽 티셔츠.jpg",
  gender: "공용 컴포트핏 라이프스타일",
  shopName : "레코드 그래픽 티셔츠",
  shopPrice : "59,000원",
  color:['white', 'black', 'pink'],
  style: ['티셔츠' ,'온라인 단독' ,'전체보기'],
  sports : ['라이프스타일'],
  size : ['95', '100' ,'105', '110'],
},
/* { 
  id: "shoplist21", 
  src: "../img/images/21.컴포트핏 인터내셔널 우븐 후드티.jpg",
  imgHidden: "../img/images/21-1.컴포트핏 인터내셔널 우븐 후드티.jpg",
  imgHidden2: "../img/images/21-2.컴포트핏 인터내셔널 우븐 후드티.jpg",
  gender: "공용 라이프스타일",
  shopName : "컴포트핏 인터내셔널 우븐 후드티",
  shopPrice : "119,000원",
},
{ 
  id: "shoplist22", 
  src: "../img/images/22.레터링 그래픽 티셔츠.jpg",
  imgHidden: "../img/images/22-1.레터링 그래픽 티셔츠.jpg",
  imgHidden2: "../img/images/22-2.레터링 그래픽 티셔츠.jpg",
  gender: "공용 컴포트핏 라이프스타일",
  shopName : "레터링 그래픽 티셔츠",
  shopPrice : "49,000원",
},
{ 
  id: "shoplist23", 
  src: "../img/images/23.컴포트핏 인터내셔널 우븐 후드티.jpg",
  imgHidden: "../img/images/23-1.컴포트핏 인터내셔널 우븐 후드티.jpg",
  imgHidden2: "../img/images/23-2.컴포트핏 인터내셔널 우븐 후드티.jpg",
  gender: "공용 라이프스타일",
  shopName : "컴포트핏 인터내셔널 우븐 후드티",
  shopPrice : "119,000원",
},
{ 
  id: "shoplist24", 
  src: "../img/images/24.플래그 반팔티.jpg",
  imgHidden: "../img/images/24-1.플래그 반팔티.jpg",
  imgHidden2: "../img/images/24-2.플래그 반팔티.jpg",
  gender: "공용 컴포트핏 라이프스타일",
  shopName : "플래그 반팔티",
  shopPrice : "39,000원",
},
{ 
  id: "shoplist25", 
  src: "../img/images/25.테니스 퍼포먼스 배색 카라티셔츠.jpg",
  imgHidden: "../img/images/25-1.테니스 퍼포먼스 배색 카라티셔츠.jpg",
  imgHidden2: "../img/images/25-2.테니스 퍼포먼스 배색 카라티셔츠.jpg",
  gender: "공용 레귤러핏 테니스 지속가능소재",
  shopName : "테니스 퍼포먼스 배색 카라티셔츠",
  shopPrice : "99,000원",
}, */

]


export default shopBoxData